name: enhanced_containers
version: 0.1.0
description: >-
    A collection of enhanced containers for Dart and Flutter.
    It is particularly suitable for easy providers linked to database.
homepage: https://github.com/cr-crme/enhanced_containers/
repository: https://github.com/cr-crme/enhanced_containers/

environment:
    sdk: ">=3.0.0 <4.0.0"

dependencies:
    flutter:
        sdk: flutter
    provider: ^6.1.5
    nanoid: ^1.0.0
    firebase_database: ^12.0.4
    firebase_database_mocks: ^0.8.1
    enhanced_containers_foundation:

dependency_overrides:
  enhanced_containers_foundation:
    path: plugins/enhanced_containers_foundation

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^6.0.0
